### ISSUE TITLE
Peer Assesment

### ISSUE THREAD

**Issue by daggtes** [daggtes/musicplayer#1]
Inform the part u assessed, Leave a  helpful comment as well as check out for an error and don't forget to grade it out of 5.

**Comment by yishakbiruk** [comment]
The player icons don't work also the hovering effect is not as it should be. 3.5 Out of 5

**Comment by Muhammeddawud** [comment]
i like the interface...............

**Comment by daggtes** [comment]
Thanks

**Comment by Danuh16** [comment]
It's a good work and I appreciate the concept of building this music player but some features doesn't work properly such as the icons, the shuffle......so you should work on that to make the app to its full extent.
rating 3/5
